OJ:
  build: 8
채점:
  제출폴더: hw
  입출력폴더: 테스트케이스
  코드파일모음폴더: 코드파일모음
  사진파일모음폴더: 사진파일모음
  결과파일: 채점결과.xlsx
  입력프롬프트메세지제거: false
  사진인식확장자:
  - .jpg
  - .jpeg
  - .png
  - .bmp
  - .hwp
  - .docx
  채점제외문자:
  - ' '
  소스파일검사:
  - 'input'
  - '"'
  과제인식문자:
  - '도'
  과제인식제외문자:
  - ' '
  - '**'
업로드:
  점수파일: 채점결과.xlsx
  업로드파일: 업로드.xls
  업로드종합파일: 업로드종합.xls
유사도:
  제출폴더: CodeDistance
  결과파일: 유사도결과.xlsx
  주석제거: false
  탭제거: true
  줄넘김제거: false
  제외문자:
  - ' '
  - '*'
정규화:
  다운로드폴더: 다운로드
  결과파일: 제출요약.xlsx
  출석부폴더: 분반별출석부
