OJ:
  build: 8
채점:
  #정규화된 과제 파일들이 저장될 폴더
  제출폴더: hw
  
  #입출력 테스트 케이스들을 저장하는 폴더
  입출력폴더: 테스트케이스
  
  #제출한 파일 중에 채점에 사용한 코드만 모은 폴더
  코드파일모음폴더: 코드파일모음
  
  #제출한 파일 중에 사진파일들을 모든 폴더
  사진파일모음폴더: 사진파일모음
  
  #채점 결과 파일 이름
  결과파일: 채점결과.xlsx
  
  #코드에 있는 input("Blah Blah")의 메시지를 지우는 flag
  입력프롬프트메세지제거: true
  
  사진인식확장자:
  - .jpg
  - .jpeg
  - .png
  - .bmp
  - .hwp
  - .docx
  
  #출력 메시지에서 제거할 문자 (이 경우 띄어쓰기를 전부 제거함)
  채점제외문자:
  - ' '
  
  #채점을 시도한 소스파일에 특정 코드를 사용했는지 필터링하기 위한 문자(for대신 while 사용 등...) 
  소스파일검사:
  - 'for'
  
  #제출한 여러 소스 파일중에 채점에 사용할 파일을 인식하는 문자
  과제인식문자:
  - '관부가세는'
  
  #위의 과제인식문자를 통해 소스 파일을 찾기 전에 소스코드에서 아래의 문자들을 제거시키고 검색을 시도함
  과제인식제외문자:
  - ' '
  - '*'
  
#업로드용 파일을 만드는데 필요한 대상 파일들
업로드:
  점수파일: 채점결과.xlsx
  업로드파일: 업로드.xls
  업로드종합파일: 업로드종합.xls
  

유사도:
  제출폴더: CodeDistance
  결과파일: 유사도결과.xlsx
  
  #소스코드 유사도 검사시 주석 제거 여부 flag
  주석제거: false
  
  #소스코드 유사도 검사시 tab 제거 여부 flag
  탭제거: true
  
  #소스코드 유사도 검사시 LF(\n)제거 여부 flag
  줄넘김제거: false
  
  #소스코드 유사도 검사시 제거할 특정 문자들
  제외문자:
  - ' '
  - '**'

정규화:
  다운로드폴더: 다운로드
  결과파일: 제출요약.xlsx
  출석부폴더: 분반별출석부
